Updated GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -97,25 +97,30 @@ jobs:
       with:
         xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
     
-    - name: OSCKitBasicExample - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Examples/OSCKitBasicExample/OSCKitBasicExample.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
-    - name: OSCKitBasicExample - Build
-      run: xcodebuild build -project "Examples/OSCKitBasicExample/OSCKitBasicExample.xcodeproj" -scheme "OSCKitBasicExample" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Basic Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Basic Example/Basic Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Basic Example - Build
+      run: xcodebuild build -project "Examples/Basic Example/Basic Example.xcodeproj" -scheme "Basic Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    
+    - name: Custom Type Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Custom Type Example/Custom Type Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Custom Type Example - Build
+      run: xcodebuild build -project "Examples/Custom Type Example/Custom Type Example.xcodeproj" -scheme "Custom Type Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
       
-    - name: OSCKitMethodBlocksExample - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Examples/OSCKitMethodBlocksExample/OSCKitMethodBlocksExample.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
-    - name: OSCKitMethodBlocksExample - Build
-      run: xcodebuild build -project "Examples/OSCKitMethodBlocksExample/OSCKitMethodBlocksExample.xcodeproj" -scheme "OSCKitMethodBlocksExample" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Method Blocks Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Method Blocks Example/Method Blocks Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Method Blocks Example - Build
+      run: xcodebuild build -project "Examples/Method Blocks Example/Method Blocks Example.xcodeproj" -scheme "Method Blocks Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
       
-    - name: OSCKitMethodIDsExample - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Examples/OSCKitMethodIDsExample/OSCKitMethodIDsExample.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
-    - name: OSCKitMethodIDsExample - Build
-      run: xcodebuild build -project "Examples/OSCKitMethodIDsExample/OSCKitMethodIDsExample.xcodeproj" -scheme "OSCKitMethodIDsExample" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Method IDs Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Method IDs Example/Method IDs Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Method IDs Example - Build
+      run: xcodebuild build -project "Examples/Method IDs Example/Method IDs Example.xcodeproj" -scheme "Method IDs Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
       
-    - name: OSCKitSocketExample - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Examples/OSCKitSocketExample/OSCKitSocketExample.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
-    - name: OSCKitSocketExample - Build
-      run: xcodebuild build -project "Examples/OSCKitSocketExample/OSCKitSocketExample.xcodeproj" -scheme "OSCKitSocketExample" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Socket Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Socket Example/Socket Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Socket Example - Build
+      run: xcodebuild build -project "Examples/Socket Example/Socket Example.xcodeproj" -scheme "Socket Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
 
 # xcodebuild test reference:
 # https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html
