Updated GitHub CI

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -24,43 +24,43 @@ on:
   schedule:
     - cron: '40 11 * * *'   # once a day @ 11:40am UTC (4:40am PST)
   
-  jobs:
-    examples:
-      name: Examples
-      runs-on: macos-latest
-      timeout-minutes: 20
-      steps:
-      - uses: actions/checkout@main
-      - uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest-stable
-    
-      - name: Custom Type - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/Custom Type/Custom OSC Type.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: Custom Type - Build
-        run: xcodebuild build -project "Examples/Custom Type/Custom OSC Type.xcodeproj" -scheme "Custom OSC Type" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    
-      - name: Method Blocks - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/Method Blocks/OSC Method Blocks.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: Method Blocks - Build
-        run: xcodebuild build -project "Examples/Method Blocks/OSC Method Blocks.xcodeproj" -scheme "OSC Method Blocks" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    
-      - name: Method IDs - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/Method IDs/OSC Method IDs.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: Method IDs - Build
-        run: xcodebuild build -project "Examples/Method IDs/OSC Method IDs.xcodeproj" -scheme "OSC Method IDs" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    
-      - name: TCP Client and Server - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/TCP Client and Server/OSC TCP Client and Server.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: TCP Client and Server - Build
-        run: xcodebuild build -project "Examples/TCP Client and Server/OSC TCP Client and Server.xcodeproj" -scheme "OSC TCP Client and Server" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    
-      - name: UDP Client and Server - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/UDP Client and Server/OSC UDP Client and Server.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: UDP Client and Server - Build
-        run: xcodebuild build -project "Examples/UDP Client and Server/OSC UDP Client and Server.xcodeproj" -scheme "OSC UDP Client and Server" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    
-      - name: UDP Socket - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-        run: xcodebuild -project "Examples/UDP Socket/OSC UDP Socket.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      - name: UDP Socket - Build
-        run: xcodebuild build -project "Examples/UDP Socket/OSC UDP Socket.xcodeproj" -scheme "OSC UDP Socket" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+jobs:
+  examples:
+    name: Build Examples
+    runs-on: macos-latest
+    timeout-minutes: 20
+    steps:
+    - uses: actions/checkout@main
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable
+  
+    - name: Custom Type - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Custom Type/Custom OSC Type.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: Custom Type - Build
+      run: xcodebuild build -project "Examples/Custom Type/Custom OSC Type.xcodeproj" -scheme "Custom OSC Type" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  
+    - name: Method Blocks - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Method Blocks/OSC Method Blocks.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: Method Blocks - Build
+      run: xcodebuild build -project "Examples/Method Blocks/OSC Method Blocks.xcodeproj" -scheme "OSC Method Blocks" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  
+    - name: Method IDs - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/Method IDs/OSC Method IDs.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: Method IDs - Build
+      run: xcodebuild build -project "Examples/Method IDs/OSC Method IDs.xcodeproj" -scheme "OSC Method IDs" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  
+    - name: TCP Client and Server - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/TCP Client and Server/OSC TCP Client and Server.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: TCP Client and Server - Build
+      run: xcodebuild build -project "Examples/TCP Client and Server/OSC TCP Client and Server.xcodeproj" -scheme "OSC TCP Client and Server" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  
+    - name: UDP Client and Server - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/UDP Client and Server/OSC UDP Client and Server.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: UDP Client and Server - Build
+      run: xcodebuild build -project "Examples/UDP Client and Server/OSC UDP Client and Server.xcodeproj" -scheme "OSC UDP Client and Server" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  
+    - name: UDP Socket - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/UDP Socket/OSC UDP Socket.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: UDP Socket - Build
+      run: xcodebuild build -project "Examples/UDP Socket/OSC UDP Socket.xcodeproj" -scheme "OSC UDP Socket" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
